import { endOfMonth,format,isAfter,isBefore,parseISO,startOfMonth } from 'date-fns';import type { Account,Budget,Category,Goal,Transaction } from '../types/finance';
export function monthTransactions(t:Transaction[],date=new Date()){const start=startOfMonth(date),end=endOfMonth(date);return t.filter(i=>{const d=parseISO(i.date);return !isBefore(d,start)&&!isAfter(d,end)&&i.status!=='cancelled';});}
export function totals(t:Transaction[]){return t.reduce((a,i)=>{if(i.status==='cancelled'||i.type==='transfer')return a;if(i.type==='income')a.income+=i.amount;if(i.type==='expense')a.expense+=i.amount;a.result=a.income-a.expense;return a;},{income:0,expense:0,result:0});}
export const totalBalance=(a:Account[])=>a.filter(x=>x.active).reduce((s,x)=>s+x.balance,0);
export function categoryTotals(t:Transaction[],c:Category[]){const e=t.filter(i=>i.type==='expense'&&i.status!=='cancelled');return c.map(x=>({name:x.name,color:x.color,value:e.filter(i=>i.categoryId===x.id).reduce((s,i)=>s+i.amount,0)})).filter(x=>x.value>0).sort((a,b)=>b.value-a.value);}
export function upcomingBills(t:Transaction[],limit=8){const today=new Date();return t.filter(i=>i.type==='expense'&&i.status==='pending'&&i.dueDate).sort((a,b)=>(a.dueDate??'').localeCompare(b.dueDate??'')).filter(i=>!i.dueDate||isAfter(parseISO(i.dueDate),today)||format(parseISO(i.dueDate),'yyyy-MM-dd')===format(today,'yyyy-MM-dd')).slice(0,limit);}
export const spentByCategory=(t:Transaction[],categoryId:string,month:string)=>t.filter(i=>i.type==='expense'&&i.categoryId===categoryId&&i.date.startsWith(month)&&i.status!=='cancelled').reduce((s,i)=>s+i.amount,0);
export function budgetProgress(b:Budget,t:Transaction[]){const spent=spentByCategory(t,b.categoryId,b.month);return{spent,percentage:b.limit>0?Math.min(spent/b.limit*100,999):0};}
export const goalProgress=(g:Goal)=>g.target>0?Math.min(g.current/g.target*100,100):0;
export function forecastBalance(a:Account[],t:Transaction[],days=30){const now=new Date(),horizon=new Date(now);horizon.setDate(horizon.getDate()+days);return t.filter(i=>i.status==='pending'&&i.dueDate&&!isBefore(parseISO(i.dueDate),now)&&!isAfter(parseISO(i.dueDate),horizon)).reduce((b,i)=>i.type==='income'?b+i.amount:i.type==='expense'?b-i.amount:b,totalBalance(a));}
export function generateInsights(t:Transaction[],a:Account[],b:Budget[],g:Goal[]){const currentTotals=totals(monthTransactions(t)),forecast=forecastBalance(a,t);const out:Array<{level:'positive'|'warning'|'critical';title:string;text:string}>=[];if(currentTotals.result>0)out.push({level:'positive',title:'Resultado mensal positivo',text:`Você preservou ${Math.round(currentTotals.result/Math.max(currentTotals.income,1)*100)}% das receitas deste mês.`});else out.push({level:'critical',title:'Despesas acima das receitas',text:'Revise despesas variáveis e vencimentos.'});if(forecast<0)out.push({level:'critical',title:'Saldo negativo projetado',text:'Os compromissos dos próximos 30 dias superam o saldo.'});const exceeded=b.filter(x=>budgetProgress(x,t).percentage>=100);if(exceeded.length)out.push({level:'warning',title:'Orçamento ultrapassado',text:`${exceeded.length} categoria(s) ultrapassaram o limite.`});const closest=[...g].sort((x,y)=>goalProgress(y)-goalProgress(x))[0];if(closest)out.push({level:'positive',title:`${Math.round(goalProgress(closest))}% da meta concluída`,text:`Continue reservando recursos para “${closest.name}”.`});return out.slice(0,6);}
