version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: monthly
      day: monday
      time: "09:00"
      timezone: "America/Bahia"

  - package-ecosystem: cargo
    directory: "/src-tauri"
    open-pull-requests-limit: 0
    schedule:
      interval: monthly
      day: wednesday
      time: "09:00"
      timezone: "America/Bahia"

  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: monthly
      day: friday
      time: "09:00"
      timezone: "America/Bahia"
