import type { ReactNode } from 'react';
import { CalendarClock, CircleDollarSign, FileScan, Lightbulb, TrendingDown, TrendingUp, Wallet } from 'lucide-react';
import { Link } from 'react-router-dom';
import { BalanceChart, CategoryChart, IncomeExpenseChart } from '../components/charts/FinanceCharts';
import { Card, CardHeader } from '../components/ui';
import { categoryTotals, generateInsights, monthTransactions, totalBalance, totals, upcomingBills } from '../lib/finance';
import { toCurrency } from '../lib/currency';
import { useFinanceStore } from '../store/useFinanceStore';
function Metric({icon,title,value,subtitle,tone}:{icon:ReactNode;title:string;value:string;subtitle:string;tone:string}){return <Card className={`metric-card ${tone}`}><span className="metric-icon">{icon}</span><div><small>{title}</small><strong>{value}</strong><em>{subtitle}</em></div></Card>}
export function DashboardPage(){const{transactions,accounts,categories,budgets,goals,documents}=useFinanceStore();const current=monthTransactions(transactions),summary=totals(current),balance=totalBalance(accounts),categoriesData=categoryTotals(current,categories),bills=upcomingBills(transactions,5),insights=generateInsights(transactions,accounts,budgets,goals);return <div className="page dashboard-page"><div className="metrics-grid"><Metric icon={<Wallet/>} title="Saldo disponível" value={toCurrency(balance)} subtitle="Em todas as contas" tone="green"/><Metric icon={<TrendingUp/>} title="Receitas do mês" value={toCurrency(summary.income)} subtitle="8,5% acima do mês anterior" tone="green-soft"/><Metric icon={<TrendingDown/>} title="Despesas do mês" value={toCurrency(summary.expense)} subtitle="5,2% abaixo do mês anterior" tone="red"/><Metric icon={<CircleDollarSign/>} title="Resultado do mês" value={toCurrency(summary.result)} subtitle="Fluxo líquido realizado" tone="blue"/><Metric icon={<CalendarClock/>} title="Contas a vencer" value={toCurrency(bills.reduce((s,b)=>s+b.amount,0))} subtitle={`${bills.length} títulos próximos`} tone="amber"/></div><div className="dashboard-grid"><Card className="span-2"><CardHeader title="Receitas x despesas" description="Comparativo dos últimos seis meses"/><IncomeExpenseChart/></Card><Card><CardHeader title="Despesas por categoria" description="Distribuição no mês atual"/><CategoryChart data={categoriesData}/></Card><Card><CardHeader title="Próximos vencimentos" action={<Link to="/contas-a-pagar">Ver todos</Link>}/><div className="due-list">{bills.map(b=><div key={b.id}><span className="due-icon"><CalendarClock/></span><span><strong>{b.description}</strong><small>{b.dueDate?new Date(`${b.dueDate}T12:00:00`).toLocaleDateString('pt-BR'):''}</small></span><em>{toCurrency(b.amount)}</em></div>)}</div></Card><Card className="span-2"><CardHeader title="Evolução do saldo" description="Crescimento consolidado"/><BalanceChart/></Card><Card><CardHeader title="Insights para você" action={<Link to="/inteligencia">Ver todos</Link>}/><div className="insight-list">{insights.slice(0,3).map(i=><div key={i.title} className={`insight ${i.level}`}><Lightbulb/><span><strong>{i.title}</strong><small>{i.text}</small></span></div>)}</div></Card><Card className="document-summary"><CardHeader title="Central de documentos" description="OCR e leitura inteligente" action={<Link to="/documentos">Abrir</Link>}/><div className="doc-summary-body"><FileScan size={38}/><strong>{documents.length} documento(s)</strong><span>{documents.filter(d=>d.status==='review').length} aguardando revisão</span></div></Card></div></div>}
